default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: db
  port: 5432
  database: homophone_development
  password: 39ng98rhg248hfo218
  user: postgres_root
  timeout: 15000

test:
  <<: *default
  host: db
  port: 5432
  database: homophone_test
  password: 39ng98rhg248hfo218
  user: postgres_root
  timeout: 15000
